Resources:
  S3S3Bucket7FFF7EB1:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: s3bucket-test-27112005
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: aws-cdk:auto-delete-objects
          Value: "true"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: FrondendStack/S3/S3Bucket/Resource
  S3S3BucketPolicy239B33FE:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3S3Bucket7FFF7EB1
      PolicyDocument:
        Statement:
          - Action:
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:List*
              - s3:PutBucketPolicy
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
                  - Arn
            Resource:
              - Fn::GetAtt:
                  - S3S3Bucket7FFF7EB1
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - S3S3Bucket7FFF7EB1
                        - Arn
                    - /*
          - Action: s3:GetObject
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":cloudfront::"
                      - Ref: AWS::AccountId
                      - :distribution/
                      - Ref: CloudFrontDistributionEAB06B35
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - S3S3Bucket7FFF7EB1
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: FrondendStack/S3/S3Bucket/Policy/Resource
  S3S3BucketAutoDeleteObjectsCustomResource7F644502:
    Type: Custom::S3AutoDeleteObjects
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
          - Arn
      BucketName:
        Ref: S3S3Bucket7FFF7EB1
    DependsOn:
      - S3S3BucketPolicy239B33FE
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: FrondendStack/S3/S3Bucket/AutoDeleteObjectsCustomResource/Default
  CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: FrondendStack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Role
  CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6.zip
      Timeout: 900
      MemorySize: 128
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
          - Arn
      Runtime: nodejs24.x
      Description:
        Fn::Join:
          - ""
          - - "Lambda function for auto-deleting objects in "
            - Ref: S3S3Bucket7FFF7EB1
            - " S3 bucket."
    DependsOn:
      - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
    Metadata:
      aws:cdk:path: FrondendStack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler
      aws:asset:path: asset.faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
      aws:asset:property: Code
  CloudFrontDistributionOrigin1S3OriginAccessControl3ECDEEE4:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: FrondendStackCloudFrontDistrOrigin1S3OriginAccessControlD768169A
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
    Metadata:
      aws:cdk:path: FrondendStack/CloudFront/Distribution/Origin1/S3OriginAccessControl/Resource
  CloudFrontDistributionEAB06B35:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: FrondendStackCloudFrontDistributionOrigin1E328812D
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName:
              Fn::GetAtt:
                - S3S3Bucket7FFF7EB1
                - RegionalDomainName
            Id: FrondendStackCloudFrontDistributionOrigin1E328812D
            OriginAccessControlId:
              Fn::GetAtt:
                - CloudFrontDistributionOrigin1S3OriginAccessControl3ECDEEE4
                - Id
            S3OriginConfig:
              OriginAccessIdentity: ""
    Metadata:
      aws:cdk:path: FrondendStack/CloudFront/Distribution/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/6VSS2/bMAz+LeWxULQ1AXbwLY+iu6w1kmMQFLLMJEpsMyApZ4Hh/z7YTrNgD2DAThL4Ufwe1NiOvzzZzw/uLCOfH0dFyGyzUuePxp3lvZGJbWbRH1HXDWT95dWVCAk8goGsIH9MY1YEP/UeRa51rDxfThqoggRWk/dv09fpy/MCDNTIEqjCHJKtKwQNMJZUuyKlIvgLJJCjKNMFDLiotMACFd+yA3oVSJQjthsz31Y3UWX4HjqaeweddJnYHhI7tE5/m9ZuzAAN3DeDvYl7lhv+r1zDg5U6xRKrnqo1vqCYb5kqtc0iiHLIYhfRuoEcty4WuiTSQdw1x2t9hntXB2JIGiAOu15Dh9cBz8gpk5KnnxEy5oHR60hptFc9CbQGkJl4iXKiSlAgWTfQYZ3I+LE3vsJf/wakboep0/0Qkfn/EZt2Y1aTt97U8IXmVClTsYZH6FfwB6wr3yfYtmYeRalcolBkj7fHH4V+UNRT1F86U6Y65MgzJ2imIqgrdbtQ7VpTUY72IJ/q8diOJ/bp4SAhjDhWGkq0y+H8ATj7sThAAwAA
    Metadata:
      aws:cdk:path: FrondendStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  S3BucketName099EDA80:
    Value:
      Ref: S3S3Bucket7FFF7EB1
  CloudFrontCloudFrontURL2F4A1EEF:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Fn::GetAtt:
              - CloudFrontDistributionEAB06B35
              - DomainName
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

