name: Provision CDK
on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:


jobs:
  
  Provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for AWS OIDC authentication
      contents: read    # Required to clone the repository
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
            version: 11
            cache: true
            cache_dependency_path: ./infrastructure/pnpm-lock.yaml

    #   - name: Set up NodeJs
    #     uses: actions/setup-node@v6
    #     with: 
    #       node-version: 22
    #       cache: 'pnpm'
    #       cache-dependency-path: infrastructure/pnpm-lock.yaml


      - name: Install dependencies
        working-directory: ./infrastructure
        run: pnpm install --frozen-lockfile

      - name: Setting public key for EC2Stack
        working-directory: ./infrastructure
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ec2-key.pub

      - name: CDK build
        working-directory: ./infrastructure
        run: npx cdk synth --all

      - name: Deploy CDK
        working-directory: ./infrastructure
        run: npx cdk deploy --require-approval never --outputs-file outputs.json --all

      - name: Upload Cloud Assembly Output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./infrastructure/outputs.json